// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tp2.Models;

namespace Tp2.Migrations
{
    [DbContext(typeof(EcoleContext))]
    [Migration("20210518093738_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tp2.Models.Filiere", b =>
                {
                    b.Property<int>("codeF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("codeSecteur")
                        .HasColumnType("int");

                    b.Property<string>("nomF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("secteurcodeSecteur")
                        .HasColumnType("int");

                    b.HasKey("codeF");

                    b.HasIndex("secteurcodeSecteur");

                    b.ToTable("filieres");
                });

            modelBuilder.Entity("Tp2.Models.Groupe", b =>
                {
                    b.Property<int>("codeG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodeF")
                        .HasColumnType("int");

                    b.Property<int?>("filierecodeF")
                        .HasColumnType("int");

                    b.Property<string>("nomG")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codeG");

                    b.HasIndex("filierecodeF");

                    b.ToTable("groupes");
                });

            modelBuilder.Entity("Tp2.Models.Module", b =>
                {
                    b.Property<int>("codeM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MassH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("codeF")
                        .HasColumnType("int");

                    b.Property<int?>("filierecodeF")
                        .HasColumnType("int");

                    b.Property<string>("nomM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codeM");

                    b.HasIndex("filierecodeF");

                    b.ToTable("modules");
                });

            modelBuilder.Entity("Tp2.Models.Secteur", b =>
                {
                    b.Property<int>("codeSecteur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nomSecteur")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codeSecteur");

                    b.ToTable("secteurs");
                });

            modelBuilder.Entity("Tp2.Models.Filiere", b =>
                {
                    b.HasOne("Tp2.Models.Secteur", "secteur")
                        .WithMany()
                        .HasForeignKey("secteurcodeSecteur");

                    b.Navigation("secteur");
                });

            modelBuilder.Entity("Tp2.Models.Groupe", b =>
                {
                    b.HasOne("Tp2.Models.Filiere", "filiere")
                        .WithMany("groupes")
                        .HasForeignKey("filierecodeF");

                    b.Navigation("filiere");
                });

            modelBuilder.Entity("Tp2.Models.Module", b =>
                {
                    b.HasOne("Tp2.Models.Filiere", "filiere")
                        .WithMany("modules")
                        .HasForeignKey("filierecodeF");

                    b.Navigation("filiere");
                });

            modelBuilder.Entity("Tp2.Models.Filiere", b =>
                {
                    b.Navigation("groupes");

                    b.Navigation("modules");
                });
#pragma warning restore 612, 618
        }
    }
}
